openapi: 3.0.3
info:
  title: "Telemetry API components"
  description: "The common telemetry API components"
  version: 1.0.0
paths: {}
components:
  schemas:
    Process:
      description: The process.
      type: object
      properties:
        process_id:
          type: string
        exe:
          type: string
        username:
          type: string
        realname:
          type: string
        computer:
          type: string
        distro:
          type: string
        cpu_brand:
          type: string
        tsc_frequency:
          type: string
        start_time:
          type: string
          format: date-time
        start_ticks:
          type: string
        parent_process_id:
          type: string
      required:
        - process_id
        - exe
        - username
        - realname
        - computer
        - distro
        - cpu_brand
        - tsc_frequency
        - start_time
        - start_ticks
        - parent_process_id
    Stream:
      description: The stream.
      type: object
      properties:
        stream_id:
          type: string
        process_id:
          type: string
        dependencies_metadata:
          $ref: "#/components/schemas/ContainerMetadata"
        objects_metadata:
          $ref: "#/components/schemas/ContainerMetadata"
        tags:
          type: array
          items:
            type: string
      additionalProperties:
        type: string
      required:
        - stream_id
        - process_id
        - tags
        - properties
    ContainerMetadata:
      description: The container metadata.
      type: object
      properties:
        types:
          type: array
          items:
            $ref: "#/components/schemas/UserDefinedType"
      required:
        - types
    UserDefinedType:
      description: The user defined type.
      type: object
      properties:
        name:
          type: string
        size:
          type: string
        members:
          type: array
          items:
            $ref: "#/components/schemas/UdtMember"
        is_reference:
          type: boolean
      required:
        - name
        - size
        - members
        - is_reference
    UdtMember:
      description: The user defined type member.
      type: object
      properties:
        name:
          type: string
        type_name:
          type: string
        offset:
          type: string
        size:
          type: string
        is_reference:
          type: boolean
      required:
        - name
        - type_name
        - offset
        - size
        - is_reference
