[package]
name = "binary-resource"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lgn-content-store = { path = "../../lgn-content-store", version = "0.1.0" }
lgn-data-runtime = { path = "../../lgn-data-runtime", version = "0.1.0" }
lgn-data-model = { path = "../../lgn-data-model", version = "0.1.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_bytes = "0.11"

[lib]
doc = false
