[workspace]
members = ["core", "modules/*", "apps/*", "tests/*"]
resolver = "2"

[profile.release]
opt-level = 3
debug = true
debug-assertions = false

[profile.bench]
opt-level = 3
debug = true
debug-assertions = false
