[workspace]
members = ["client/*", "server/*", "core/*", "lib/*", "plugin/*", "test/*"]
exclude = ["test/sample_data"]

[profile.release]
opt-level = 3
debug = true
debug-assertions = false

[profile.bench]
opt-level = 3
debug = true
debug-assertions = false
