[editor_server]
# Configuration for the editor server (editor-srv)

# The project root directory.
#
# If relative, it is relative to the current working directory.
#
# Default:
#project_root = "tests/sample-data"

# The endpoint to listen on.
#
# Default:
#listen_endpoint = "[::1]:50001"

# The scene to load.
scene = "/world/sample_1.ent"

# The address to database hosting build results.
#
# Two kinds of paths are supported:
# * An address to a mysql instance (i.e.: "mysql://user:pass@127.0.0.1:6603/")
# * Directory path for local sqlite database. (i.e.: "tests/sample-data/temp/")
build_output = "tests/sample-data/temp/"

[runtime_srv]
project_dir = "tests/sample-data"
server_addr = "[::1]:50052"

[physics]
enable_visual_debugger = false
length_tolerance = 1.0
speed_tolerance = 1.0

[streamer]
max_frame_time = 33_000 #microsec

[data_transaction]
log_operation = false

[logging]
#logs_buffer_size = 10485760
#metrics_buffer_size = 1048576
#threads_buffer_size = 10485760
#max_level_filter = "ERROR"

[logging.level_filters]
#webrtc = "WARN"

[online]
api_base_url = "https://api.live.playground.legionlabs.com"
web_api_base_url = "https://web-api.live.playground.legionlabs.com"

# This section is used by clients.
[online.authentication.oauth]
issuer_url = "https://cognito-idp.ca-central-1.amazonaws.com/ca-central-1_SkZKDimWz"
client_id = "5m58nrjfv6kr144prif9jk62di"
redirect_uri = "http://localhost:3000/"

# This section is used by servers.
[online.signature_validation.aws_cognito]
region = "ca-central-1"
user_pool_id = "ca-central-1_SkZKDimWz"

[source_control.repository_index]
type = "local"
path = "/tmp/repository-index"

#[content_store.persistent.provider.grpc]
[content_store.persistent.provider.local]
path = "tests/sample-data/temp"

[[content_store.persistent.caching_providers]]
[content_store.persistent.caching_providers.lru]
size = 250

[content_store.volatile.provider.local]
path = "tests/sample-data/temp"

[[content_store.volatile.caching_providers]]
[content_store.volatile.caching_providers.lru]
size = 250

[source_control.server.database]
host = "localhost"
username = "root"
password = "password"
