[package]
name = "lgn-web-client"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
directories = "4"
lgn-online = { path = "../lgn-online", version = "0.1.0" }
napi = { version = "2.2.0", features = ["tokio_rt", "serde-json"] }
napi-derive = "2.2.0"
once_cell = "1.10.0"
serde_json = "1.0"
http = "0.2"
thiserror = "1.0.30"

[dev-dependencies]
tokio = { version = "1.13", features = [
    "macros",
    "rt-multi-thread",
    "tracing",
] }

[build-dependencies]
napi-build = "1.2.1"
