[package]
name = "lgn-api-codegen-node"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
lgn-api-codegen = { path = "../lgn-api-codegen", version = "0.1.0" }
napi = { version = "2.4.3", features = ["tokio_rt", "serde-json"] }
napi-derive = "2.4.1"

[build-dependencies]
napi-build = "2.0.0"
