openapi: 3.1.0
info:
  title: "Property Inspector API"
  description: "The OpenAPI specification for the Legion Labs property inspector."
  version: 1.0.0
paths:
  /v1/spaces/{space-id}/workspaces/{workspace-id}/resources/{resource-id}/properties/:
    parameters:
      - $ref: "../../lgn-governance/apis/space.yaml#/components/parameters/space_id"
      - $ref: "../../lgn-governance/apis/workspace.yaml#/components/parameters/workspace_id"
      - $ref: "#/components/parameters/resource_id"
    get:
      description: Get all properties.
      operationId: getProperties
      responses:
        "200":
          description: The properties
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResourceDescriptionProperties"
        "404":
          description: Resource not found
    put:
      description: Update a set of properties.
      operationId: updateProperties
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PropertyUpdates"
      responses:
        "204":
          description: Resource properties updated
        "404":
          description: Resource not found

  /v1/spaces/{space-id}/workspaces/{workspace-id}/resources/{resource-id}/properties/array/:
    parameters:
      - $ref: "../../lgn-governance/apis/space.yaml#/components/parameters/space_id"
      - $ref: "../../lgn-governance/apis/workspace.yaml#/components/parameters/workspace_id"
      - $ref: "#/components/parameters/resource_id"
    post:
      description: Insert new item in a properties' array.
      operationId: insertPropertyArrayItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InsertPropertyArrayItem"
      responses:
        "200":
          description: Inserted item property
          content:
            application/json:
              schema:
                type: object
                properties:
                  new_value:
                    $ref: "#/components/schemas/ResourceProperty"
        "404":
          description: Resource not found
    delete:
      description: Delete an item in a properties' array.
      operationId: deletePropertiesArrayItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeletePropertyArrayItem"
      responses:
        "204":
          description: Item deleted
        "404":
          description: Resource not found

  /v1/spaces/{space-id}/workspaces/{workspace-id}/resources/{resource-id}/properties/array/reorder/:
    parameters:
      - $ref: "../../lgn-governance/apis/space.yaml#/components/parameters/space_id"
      - $ref: "../../lgn-governance/apis/workspace.yaml#/components/parameters/workspace_id"
      - $ref: "#/components/parameters/resource_id"
    post:
      description: Reorder a properties' array.
      operationId: reorderPropertyArray
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReorderPropertyArray"
      responses:
        "204":
          description: Item reordered
        "404":
          description: Resource not found

  /v1/spaces/{space-id}/workspaces/{workspace-id}/resources/{resource-id}/properties/selection-update/:
    parameters:
      - $ref: "../../lgn-governance/apis/space.yaml#/components/parameters/space_id"
      - $ref: "../../lgn-governance/apis/workspace.yaml#/components/parameters/workspace_id"
      - $ref: "#/components/parameters/resource_id"
    post:
      description: Update the selection.
      operationId: updatePropertySelection
      responses:
        "204":
          description: Selection updated
        "404":
          description: Resource not found

  /v1/spaces/{space-id}/workspaces/{workspace-id}/properties/dynamic-traits:
    parameters:
      - $ref: "../../lgn-governance/apis/space.yaml#/components/parameters/space_id"
      - $ref: "../../lgn-governance/apis/workspace.yaml#/components/parameters/workspace_id"
    get:
      description: Get all the available dynamic traits.
      operationId: getAvailableDynTraits
      parameters:
        - name: trait_name
          in: query
          description: Filter the dynamic traits by name.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The dynamic traits
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

components:
  parameters:
    resource_id:
      name: resource-id
      in: path
      description: The resource identifier.
      required: true
      schema:
        $ref: "#/components/schemas/ResourceId"
  schemas:
    ResourceId:
      description: An identifier to a unique a resource.
      type: string
    ResourceDescription:
      description: A resource description
      type: object
      properties:
        id:
          type: string
        path:
          type: string
        version:
          type: integer
          format: uint32
        type:
          type: string
      required:
        - id
        - path
        - version
        - type
    ResourceProperty:
      type: object
      properties:
        name:
          type: string
        ptype:
          type: string
        json_value:
          type: string
        sub_properties:
          type: array
          items:
            $ref: "#/components/schemas/ResourceProperty"
        attributes:
          type: object
          additionalProperties:
            type: string
      required:
        - name
        - ptype
        - sub_properties
        - attributes
    ResourceDescriptionProperties:
      description: A resources with all its properties
      type: object
      properties:
        description:
          $ref: "#/components/schemas/ResourceDescription"
        properties:
          type: array
          items:
            $ref: "#/components/schemas/ResourceProperty"
      required:
        - description
        - properties
    PropertyUpdate:
      description: A property update
      type: object
      properties:
        name:
          type: string
        json_value:
          type: string
      required:
        - name
        - json_value
    PropertyUpdates:
      description: A set of property updates
      type: object
      properties:
        id:
          type: string
        version:
          type: integer
          format: uint32
        updates:
          type: array
          items:
            $ref: "#/components/schemas/PropertyUpdate"
      required:
        - id
        - version
        - updates
    DeletePropertyArrayItem:
      type: object
      properties:
        array_path:
          type: string
        indices:
          type: array
          items:
            type: integer
            format: uint64
      required:
        - array_path
        - indeces
    InsertPropertyArrayItem:
      type: object
      properties:
        array_path:
          type: string
        index:
          type: integer
          format: uint64
        json_value:
          type: string
      required:
        - array_path
        - index
    ReorderPropertyArray:
      type: object
      properties:
        array_path:
          type: string
        old_index:
          type: integer
          format: uint64
        new_index:
          type: integer
          format: uint64
