openapi: 3.0.3
info:
  title: "Resource Browser API"
  description: "The OpenAPI specification for the Legion Labs resource browser."
  version: 1.0.0
paths:
  /v1/spaces/{space-id}/workspaces/{workspace-id}/resources/search/{token}:
    parameters:
      - $ref: "../../lgn-governance/apis/space.yaml#/components/parameters/space_id"
      - $ref: "../../lgn-governance/apis/workspace.yaml#/components/parameters/workspace_id"
      - $ref: "#/components/parameters/token"
    get:
      description: Search Resources
      operationId: SearchResources
      responses:
        "200":
          description: Ok.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NextSearchToken"
  /v1/spaces/{space-id}/workspaces/{workspace-id}/resources:
    parameters:
      - $ref: "../../lgn-governance/apis/space.yaml#/components/parameters/space_id"
      - $ref: "../../lgn-governance/apis/workspace.yaml#/components/parameters/workspace_id"
    get:
      description: Get the list of all the resources types available (for creation dialog)
      operationId: GetResourceTypeNames
      responses:
        "200":
          description: Ok.
          content:
            application/json:
              schema:
                type: object
                properties:
                  resource_types:
                    type: array
                    items:
                      type: string
                required:
                  - resource_types
    post:
      description: Create a resource
      operationId: CreateResource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                resource_type:
                  type: string
                resource_name:
                  type: string
                parent_resource_id:
                  type: string
                init_values:
                  type: array
                  items:
                    $ref: "#/components/schemas/InitPropertyValue"
                upload_id:
                  type: string
              required:
                - resource_type
                - init_values
      responses:
        "200":
          description: Ok.
          content:
            application/json:
              schema:
                type: object
                properties:
                  new_id:
                    type: string
                required:
                  - new_id
    delete:
      description: Delete a resource
      operationId: DeleteResource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
                - id
      responses:
        "204":
          description: Ok.
    put:
      description: Rename a resource
      operationId: RenameResource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                new_path:
                  type: string
              required:
                - id
                - new_path
      responses:
        "204":
          description: Ok.
  /v1/spaces/{space-id}/workspaces/{workspace-id}/resources/clone:
    parameters:
      - $ref: "../../lgn-governance/apis/space.yaml#/components/parameters/space_id"
      - $ref: "../../lgn-governance/apis/workspace.yaml#/components/parameters/workspace_id"
    post:
      description: Clone a resource
      operationId: CloneResource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                source_id:
                  type: string
                target_parent_id:
                  type: string
                init_values:
                  type: array
                  items:
                    $ref: "#/components/schemas/InitPropertyValue"
              required:
                - source_id
                - init_values
      responses:
        "200":
          description: Ok.
          content:
            application/json:
              schema:
                type: object
                properties:
                  new_resource:
                    $ref: "#/components/schemas/ResourceDescription"
                required:
                  - new_resource
  /v1/spaces/{space-id}/workspaces/{workspace-id}/resources/reparent:
    parameters:
      - $ref: "../../lgn-governance/apis/space.yaml#/components/parameters/space_id"
      - $ref: "../../lgn-governance/apis/workspace.yaml#/components/parameters/workspace_id"
    post:
      description: Reparent a resource
      operationId: ReparentResource
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                new_path:
                  type: string
              required:
                - id
                - new_path
      responses:
        "204":
          description: Ok.

components:
  parameters:
    token:
      name: token
      in: path
      description: The resource to search for.
      required: true
      schema:
        $ref: "#/components/schemas/Token"
  schemas:
    Token:
      description: Token to search for
      type: string
    NextSearchToken:
      description: The following search token
      type: object
      properties:
        next_search_token:
          type: string
        total:
          type: integer
          format: uint32
        resource_description:
          type: array
          items:
            $ref: "#/components/schemas/ResourceDescription"
      required:
        - next_search_token
        - total
        - resource_description
    ResourceDescription:
      description: Description of a resource
      type: object
      properties:
        id:
          type: string
        path:
          type: string
        version:
          type: integer
        type:
          type: string
      required:
        - id
        - path
        - version
        - type
    InitPropertyValue:
      description: Init Property value
      type: object
      properties:
        property_path:
          type: string
        json_value:
          type: string
      required:
        - property_path
        - json_value
