[package]
name = "lgn-build-utils-web"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_toml = "0.11.3"
lgn-build-utils = { path = "../lgn-build-utils", version = "0.1.0" }
named-lock = "0.1"
serde = { version = "1.0.136", features = ["derive"] }
which = "4.2"
