[package]
name = "lgn-compiler-debugcube"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
doc = false

[[bin]]
name = "compiler-debugcube"
path = "src/main.rs"
doc = false

[dependencies]
lgn-data-offline = { path = "../lgn-data-offline", version = "0.1.0" }
lgn-data-runtime = { path = "../lgn-data-runtime", version = "0.1.0" }
lgn-data-compiler = { path = "../lgn-data-compiler", version = "0.1.0" }
generic-data = { path = "../../tests/generic-data", version = "0.1.0", features = [
    "offline",
    "runtime",
] }
bincode = "1.3.3"

[build-dependencies]
lgn-data-codegen = { path = "../lgn-data-codegen", version = "0.1.0" }
