[package]
name = "proto-graph"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lgn-math = { path = "../../crates/lgn-math", version = "0.1.0" }
uuid = { version = "1.0", features = ["serde", "v4"] }
downcast-rs = "1.2"
