[package]
name = "lgn-async-span-fn"
version = "0.1.0"
edition = "2021"
homepage = "https://legionengine.com"
repository = "https://github.com/legion-labs/legion"
license = "MIT OR Apache-2.0"

[dependencies]
lgn-telemetry-sink = { path = "../lgn-telemetry-sink", version = "0.1.0" }
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0" }
tokio = { version = "1", features = ["full"] }

tracing = "0.1.34"
tracing-subscriber = "0.3.11"
tracing-opentelemetry = "0.17.2"
opentelemetry = { version = "0.17", default-features = false, features = [
    "trace",
] }
opentelemetry-jaeger = "0.16.0"
