[package]
name = "lgn-animation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# legion
lgn-app = { path = "../lgn-app", version = "0.1.0" }
lgn-core = { path = "../lgn-core", version = "0.1.0" }
lgn-data-model = { path = "../lgn-data-model", version = "0.1.0" }
lgn-data-runtime = { path = "../lgn-data-runtime", version = "0.1.0" }
lgn-ecs = { path = "../lgn-ecs", version = "0.1.0" }
lgn-math = { path = "../lgn-math", version = "0.1.0" }
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0" }
lgn-graphics-renderer = { path = "../lgn-graphics-renderer", version = "0.1.0" }
lgn-graphics-data = { path = "../lgn-graphics-data", version = "0.1.0" }
lgn-transform = { path = "../lgn-transform", version = "0.1.0" }

# other
chrono = "0.4"

[build-dependencies]
lgn-data-codegen = { path = "../lgn-data-codegen", version = "0.1.0" }
