[package]
name = "lgn-governance"
description = "Governance service to manage users, spaces, workspaces and sessions."
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lgn_governance"
path = "src/lib.rs"

[[bin]]
name = "lgn_governance_srv"
path = "src/bin/server.rs"
required-features = ["server"]

[features]
default = ["server"]
server = ["clap", "lgn-cli-utils", "lgn-telemetry-sink"]

[dependencies]
anyhow = "1"
async-trait = "0.1"
axum = "0.5"
base64 = "0.13"
chrono = "0.4"
clap = { version = "3.0", features = ["derive"], optional = true }
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
lgn-cli-utils = { path = "../lgn-cli-utils", version = "0.1.0", optional = true }
lgn-online = { path = "../lgn-online", version = "0.1.0" }
lgn-telemetry-sink = { path = "../lgn-telemetry-sink", version = "0.1.0", optional = true }
lgn-tracing = { path = "../../crates/lgn-tracing", version = "0.1.0" }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_qs = { version = "0.9", features = ["axum"] }
thiserror = "1"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
lgn-api-codegen = { path = "../lgn-api-codegen", version = "0.1.0" }
