[package]
name = "lgn-graphics-cgen-runtime"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
lgn-graphics-api = { path = "../lgn-graphics-api", version = "0.1.0" }
lgn-math = { path = "../lgn-math", version = "0.1.0" }

half = "1.8.2"
