[package]
name = "lgn-compiler-material"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
doc = false

[[bin]]
name = "compiler-material"
path = "src/main.rs"
doc = false

[dependencies]
lgn-data-offline = { path = "../lgn-data-offline", version = "0.1.0" }
lgn-data-runtime = { path = "../lgn-data-runtime", version = "0.1.0" }
lgn-graphics-runtime = { path = "../lgn-graphics-runtime", version = "0.1.0" }
lgn-graphics-offline = { path = "../lgn-graphics-offline", version = "0.1.0" }
lgn-data-compiler = { path = "../lgn-data-compiler", version = "0.1.0" }
