[cargo-new]
name = "Legion Labs"
email = "devs@legionlabs.com"
vcs = "none"

[alias]
md = "run --package lgn-monorepo --bin lgn-monorepo --"
m = "run -q --release --package lgn-monorepo --bin lgn-monorepo --"
mclippy = "run -q --release --package lgn-monorepo --bin lgn-monorepo -- clippy"
mdoc = "run -q --release --package lgn-monorepo --bin lgn-monorepo -- doc"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
