[package]
name = "lsc-cli"
version = "0.1.0"
authors = ["mad-legion <mad@legionlabs.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"