[package]
name = "test-compilers"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
legion-data-compiler = { path = "../../data-compiler" }
legion-content-store = { path = "../../content-store" }
legion-resources = { path = "../../resources" }
legion-assets = { path = "../../assets" }
text-resource = { path = "../../resources/test-text-resource"}
integer-asset = { path = "../../assets/test-integer-asset"}
refs-resource = { path = "../../resources/test-refs-resource"}
refs-asset = { path = "../../assets/test-refs-asset"}

[[bin]]
name = "compiler-test-atoi"
path = "src/atoi.rs"
doc = false

[[bin]]
name = "compiler-test-reverse"
path = "src/reverse.rs"
doc = false

[[bin]]
name = "compiler-test-refs"
path = "src/refs.rs"
doc = false