[package]
name = "proto-salsa-compiler"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salsa = "0.16"
strum = "0.24"
strum_macros = "0.24"
downcast-rs = "1.2"
