[package]
name = "legion"
version = "0.1.0"
edition = "2018"
authors = [
    "Bevy Contributors <bevyengine@gmail.com>",
    "Carter Anderson <mcanders1@gmail.com>",
]
description = "An internal Legion crate used to facilitate optional dynamic linking via the 'dynamic' feature"
homepage = "https://legionengine.com"
repository = "https://github.com/legion-labs/legion"
license = "MIT OR Apache-2.0"
keywords = ["legion"]

[dependencies]
legion-app = { path = "../app", version = "0.1.0" }
legion-core = { path = "../core", version = "0.1.0" }
legion-derive = { path = "../derive", version = "0.1.0" }
legion-ecs = { path = "../ecs", version = "0.1.0" }
legion-math = { path = "../math", version = "0.1.0" }
legion-tasks = { path = "../tasks", version = "0.1.0" }
legion-transform = { path = "../transform", version = "0.1.0" }
legion-utils = { path = "../utils", version = "0.1.0" }
