[package]
name = "lgn-build-utils-proto"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
lgn-build-utils = { path = "../lgn-build-utils", version = "0.1.0" }
tonic-build = "0.6"
which = "4.2"
