[package]
name = "runtime-srv"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Legion engine

## core
legion-app = { path = "../../core/app", version = "0.1.0" }
legion-ecs = { path = "../../core/ecs", version = "0.1.0" }
legion-math = { path = "../../core/math", version = "0.1.0" }
legion-utils = { path = "../../core/utils", version = "0.1.0" }
legion-transform = { path = "../../plugin/transform", version = "0.1.0" }
legion-core = { path = "../../plugin/core", version = "0.1.0" }

## libs
legion-content-store = { path = "../../lib/content-store" }
legion-data-runtime = { path = "../../lib/data-runtime" }

# other
clap = "2.33"
ron = "0.6.4"
serde = { version = "1.0", features = ["derive"] }
