[package]
name = "lgn-compiler-runtime-entity"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
doc = false

[[bin]]
name = "compiler-runtime-entity"
path = "src/main.rs"
doc = false

[dependencies]
lgn-data-compiler = { path = "../lgn-data-compiler", version = "0.1.0" }
lgn-data-offline = { path = "../lgn-data-offline", version = "0.1.0" }
lgn-data-runtime = { path = "../lgn-data-runtime", version = "0.1.0" }
# temp dependency on sample-data, until runtime data moved to plugins
sample-data-offline = { path = "../../tests/sample-data-offline", version = "0.1.0" }
sample-data-runtime = { path = "../../tests/sample-data-runtime", version = "0.1.0" }
sample-data-compiler = { path = "../../tests/sample-data-compiler", version = "0.1.0" }
bincode = "1.3.3"
