[package]
name = "lgn-content-store2"
version = "0.1.0"
authors = ["Legion Labs <devs@legionlabs.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0"
base64 = "0.13"
byteorder = "1.4.3"
smallvec = "1.8.0"
thiserror = "1.0"
