[package]
name = "fake-log-server"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
futures = "0.3.21"
lipsum = "0.8.0"
log = "0.4.14"
poem = { version = "1.3.8", features = ["websocket"] }
poem-openapi = { version = "1.3.8", features = ["swagger-ui", "chrono"] }
rand = "0.8.5"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.9"
