[package]
name = "editor-srv"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
legion-app = { path = "../../lib/app", version = "0.1.0" }
legion-ecs = { path = "../../lib/ecs", version = "0.1.0" }
legion-async = { path = "../../plugin/async", version = "0.1.0" }
legion-editor-proto = { path = "../../proto/editor-proto", version = "0.1.0" }
legion-mp4 = { path = "../../lib/mp4", version = "0.1.0" }
legion-codec-api = { path = "../../lib/codec-api", version = "0.1.0" }
tokio = { version = "1", features = ["full"] }
tonic = "0.5.2"
clap = "2"
webrtc = "0.1.1"
interceptor = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.13.0"
anyhow = "1.0.44"
bytes = "1"
log = "0.4"
simple_logger = "1"
