[package]
name = "lgn-editor-yaml"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lgn-governance = { path = "../lgn-governance", version = "0.1.0" }
lgn-online = { path = "../lgn-online", version = "0.1.0" }
lgn-tracing = { path = "../lgn-tracing", version = "0.1.0" }

async-trait = "0.1.56"
axum = "0.5"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
serde_qs = { version = "0.9", features = ["axum"] }
thiserror = "1"


[build-dependencies]
lgn-api-codegen = { path = "../lgn-api-codegen", version = "0.1.0" }
