[book]
authors = ["Legion Labs <devs@legionlabs.com>"]
language = "en"
multilingual = false
src = "src"
title = "The Legion Engine and Pipeline Book"

[rust]
edition = "2018"

[build]
build-dir = "../target/book"
create-missing = false
