name: Benchmarks

on:
  schedule:
    # Run the job 6am and 6pm EDT
    - cron: "0 10,22 * * *"

jobs:
  bench:
    name: Running benchmarks
    strategy:
      matrix:
        include:
          - os: [self-hosted, windows, c5.4xlarge]
            container: ghcr.io/legion-labs/build-env-win-rust:0.1.0
            workdir: C:\github\workspace
          - os: [self-hosted, ubuntu]
            container: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
            workdir: /github/workspace
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build benchmarks
        run: >-
          docker run
          --name cargo_build
          --rm
          --workdir ${{ matrix.workdir }}
          -v ${{ github.workspace }}:${{ matrix.workdir }}
          ${{ matrix.container }}
          make bench-build

      - name: Run benchmarks
        run: >-
          docker run
          --name cargo_bench
          --rm
          --workdir ${{ matrix.workdir }}
          -v ${{ github.workspace }}:${{ matrix.workdir }}
          ${{ matrix.container }}
          make bench-run
  benchmark:
    name: Running benchmarks
    strategy:
      matrix:
        os:
          [
            [self-hosted, windows, base, build],
            [self-hosted, linux, base, build],
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Build benchmarks
        run: make bench-build

      - name: Run benchmarks
        run: bench-run
