name: Legion CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Running code checks
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Check for formatting
        run: cargo fmt --all -- --check 

      - name: Validate docs
        run: cargo doc --workspace

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run Cargo Deny
        run: cargo deny check

  test:
    name: Running tests
    needs: lint
    strategy:
      matrix:
        include:
          - os: windows-2019
            container: ghcr.io/legion-labs/build-env-win-rust:0.1.0
            workdir: C:\github\workspace
          - os: ubuntu-20.04
            container: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
            workdir: /github/workspace
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build
        run: >-
          docker run
          --name cargo_build
          --rm
          --workdir ${{ matrix.workdir }}
          -v ${{ github.workspace }}:${{ matrix.workdir }}
          ${{ matrix.container }}
          cargo test --no-run

      - name: Run tests
        run: >-
          docker run
          --name cargo_test
          --rm
          --workdir ${{ matrix.workdir }}
          -v ${{ github.workspace }}:${{ matrix.workdir }}
          ${{ matrix.container }}
          cargo test

      - name: Run benchmarks
        run: >-
          docker run
          --name cargo_bench
          --rm
          --workdir ${{ matrix.workdir }}
          -v ${{ github.workspace }}:${{ matrix.workdir }}
          ${{ matrix.container }}
          cargo bench
