name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Running code checks
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Check for formatting
        run: cargo fmt --all -- --check

      - name: Run Check
        run: cargo check --locked --all-targets --all-features

      - name: Run Clippy
        run: cargo clippy --locked --all-targets --all-features -- -D warnings

      - name: Run Cargo Deny
        run: cargo deny check

  test:
    name: Running tests
    needs: lint
    strategy:
      matrix:
        include:
          - os: windows-2019
            container: ghcr.io/legion-labs/build-env-win-rust:0.1.0
            workdir: C:\github\workspace
          - os: ubuntu-20.04
            container: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
            workdir: /github/workspace
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: >-
          docker run
          --name cargo_build
          --rm
          --workdir ${{ matrix.workdir }}
          -v ${{ github.workspace }}:${{ matrix.workdir }}
          ${{ matrix.container }}
          cargo test --no-run

      - name: Run tests
        run: >-
          docker run
          --name cargo_test
          --rm
          --workdir ${{ matrix.workdir }}
          -v ${{ github.workspace }}:${{ matrix.workdir }}
          ${{ matrix.container }}
          cargo test

  bench:
    name: Running benchmarks
    needs: lint
    strategy:
      matrix:
        include:
          - os: windows-2019
            container: ghcr.io/legion-labs/build-env-win-rust:0.1.0
            workdir: C:\github\workspace
          - os: ubuntu-20.04
            container: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
            workdir: /github/workspace
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run benchmarks
        run: >-
          docker run
          --name cargo_bench
          --rm
          --workdir ${{ matrix.workdir }}
          -v ${{ github.workspace }}:${{ matrix.workdir }}
          ${{ matrix.container }}
          cargo bench

  build_docs:
    name: Building docs
    needs: lint
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Build docs
        run: |
          cargo doc --workspace --no-deps --all-features
          mdbook build ./docs/
          mv ./target/book/ ./target/doc/
          echo "<meta http-equiv=\"refresh\" content=\"0; URL=book/index.html\"/>" > target/doc/index.html
    
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ./target/doc

  deploy_docs:
    name: Deploying docs
    needs: [test, bench, build_docs]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: docs
          path: ./target/doc
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/doc
          force_orphan: true
