name: Legion CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Building and running tests
    strategy:
      matrix:
        include:
          - os: windows-2019
            container: ghcr.io/legion-labs/build-env-win-rust:0.1.0
            workdir: C:\github\workspace
          - os: ubuntu-20.04
            container: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
            workdir: /github/workspace
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cargo test
        run: >-
          docker run
          --name cargo_test
          --rm
          --workdir ${{ matrix.workdir }}
          -v ${{ github.workspace }}:${{ matrix.workdir }}
          ${{ matrix.container }}
          cargo test

