name: CI - Book

on:
  push:
    paths:
      - "doc/**"
      - ".github/workflows/ci_book.yml"
    branches:
      - main

jobs:
  build_book:
    name: Building book
    runs-on: [self-hosted, ubuntu]
    container:
      image: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Build book
        run: make book

      - name: Upload book
        uses: actions/upload-artifact@v2
        with:
          name: book
          path: ./target/book
          retention-days: 5

  deploy_book:
    name: Deploying book
    needs: [build_book]
    runs-on: [self-hosted, ubuntu]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: book
          path: ./book

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        continue-on-error: true
        id: "try1"
        with:
          deploy_key: ${{ secrets.BOOK_DEPLOY_KEY }}
          external_repository: legion-labs/book.legionengine.com
          publish_branch: main
          publish_dir: ./book
          force_orphan: true
          cname: book.legionengine.com

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: steps.try1.outcome=='failure'
        with:
          deploy_key: ${{ secrets.BOOK_DEPLOY_KEY }}
          external_repository: legion-labs/book.legionengine.com
          publish_branch: main
          publish_dir: ./book
          force_orphan: true
          cname: book.legionengine.com

      - name: Cleanup
        run: ssh-agent -k