name: CI - Release

on:
  workflow_run:
    workflows: ["CI - Test"]
    types: [completed]

jobs:
  build_release:
    name: Building release binaries
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, ubuntu]
    container:
      image: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Build release
        run: make build-release

      - name: Upload release artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            ./target/release
            !./target/release/build
            !./target/release/deps
            !./target/release/incremental
          retention-days: 5

  dockerize:
    name: Building docker images and deploying them
    needs: [build_release]
    runs-on: [self-hosted, ubuntu]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: release
          path: ./target

      - name: Docker build
        run: make dockerize-release

      - name: Docker push
        run: make dockerize-push
