name: CI - Test

on:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Running code checks
    runs-on: [self-hosted, linux, common, build]
    steps:
      - uses: actions/checkout@v2

      - name: Run initial checks
        run: cargo ci check

  test:
    name: Running tests
    needs: [lint, runner_selection]
    strategy:
      matrix:
        os:
          [
            "${{ needs.check_needs_gpu_tests.outputs.linux_machine }}",
            "${{ needs.check_needs_gpu_tests.outputs.windows_machine }}",
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: cargo ci test

  build_docs:
    name: Building docs
    needs: lint
    runs-on: [self-hosted, linux, common, build]
    steps:
      - uses: actions/checkout@v2

      - name: Build docs
        run: cargo m doc

      - name: Upload docs
        uses: actions/upload-artifact@v2
        with:
          name: doc
          path: ./target/doc
          retention-days: 5

  deploy_docs:
    name: Deploying docs
    needs: [build_docs, test]
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: doc
          path: ./doc

      - run: sleep 5

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        continue-on-error: true
        with:
          deploy_key: ${{ secrets.DOCS_DEPLOY_KEY }}
          external_repository: legion-labs/api.legionengine.com
          publish_branch: main
          publish_dir: ./doc
          force_orphan: true
          cname: api.legionengine.com

  ###############################################################################

  runner_selection:
    name: Check if graphics libs changed
    runs-on: ubuntu-latest
    outputs:
      linux_runner: ${{ steps.changed-crates.outputs.linux_runner }}
      windows_runner: ${{ steps.changed-crates.outputs.windows_runner }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test changed crates
        id: changed-crates
        run: |
          crates=$(cargo m changed-since HEAD^ --matches-any renderer graphics-sandbox)
          if [[ $? != 0 ]]; then
            echo "failed to detect changed crates"
            exit 1
          fi
          echo $crates
          if [[ $crates ]]; then
            echo "::set-output name=linux_runner::[\"self-hosted\",\"linux\",\"gpu\",\"build\"]"
            echo "::set-output name=windows_runner::[[\"self-hosted\",\"windows\",\"gpu\",\"build\"]]"
          else
            echo "::set-output name=linux_runner::[[\"self-hosted\",\"linux\",\"common\",\"build\"]]"
            echo "::set-output name=windows_runner::[[\"self-hosted\",\"windows\",\"common\",\"build\"]]"
          fi
