name: Test Coverage

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"

jobs:
  coverage:
    name: Running code coverage analysis
    runs-on: [self-hosted, ubuntu]
    container:
      image: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Build and run tests
        run: make cov

      - name: Build coverage report
        run: make grcov

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./target/debug/coverage
