name: Release

on:
  schedule:
    # Run the job every 3 hours
    - cron: "0 */3 * * *"
  workflow_dispatch:
    inputs:
      name:
        description: "Release tag"
        required: false
        default: "preflight"

env:
  CARGO_TERM_COLOR: always
  LEGION_TELEMETRY_URL: ${{ secrets.LEGION_TELEMETRY_URL }}

jobs:
  build_release:
    name: Building release binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            [self-hosted, windows, common, build],
            [self-hosted, linux, common, build],
          ]
    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap
        uses: ./.github/actions/bootstrap

      - name: Build
        env:
          MONOREPO_DOCKER_REGISTRY: ${{ secrets.MONOREPO_DOCKER_REGISTRY }}
        run: cargo m dist --release --force -p analytics-web -p editor-client -p editor-srv -p telemetry-ingestion-srv -p analytics-srv -p source-control-srv

      - name: Upload Zip artifacts to github
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v2
        with:
          name: lambda-release
          path: |
            ./target/release/zip/
            !./target/release/zip/*.zip
          retention-days: 5
