name: Release Test

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Release tag"
        required: false
        default: "preflight"

jobs:
  build_release:
    name: Building release binaries
    runs-on: [self-hosted, linux, common, build]
    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap
        uses: ./.github/actions/bootstrap

      - name: Build
        env:
          MONOREPO_DOCKER_REGISTRY: ${{ secrets.MONOREPO_DOCKER_REGISTRY }}
        run: cargo m dist --release -v -p telemetry-ingestion-srv
