name: Release Web

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Release tag"
        required: false
        default: "preflight"

env:
  CARGO_TERM_COLOR: always
  LEGION_TELEMETRY_URL: ${{ secrets.LEGION_TELEMETRY_URL }}

jobs:
  build_web_release:
    name: Building release binaries
    runs-on: [self-hosted, linux, common, build]
    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap
        uses: ./.github/actions/bootstrap

      - name: Npm install
        run: cargo m npm install

      - name: Npm build
        run: cargo m npm build

      - name: Upload analytics artifacts
        uses: actions/upload-artifact@v2
        with:
          name: analytics
          path: ./crates/lgn-analytics-gui/frontend/dist
          retention-days: 5

      - name: Upload editor artifacts
        uses: actions/upload-artifact@v2
        with:
          name: editor
          path: ./crates/lgn-editor-gui/frontend/dist
          retention-days: 5

  deploy_web_release:
    name: Deploying book
    needs: build_web_release
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        app: ["analytics", "editor"]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.app }}
          path: ./${{ matrix.app }}

      - name: Deploy Analytics
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ANALYTICS_DEPLOY_KEY }}
          external_repository: legion-labs/${{ matrix.app }}.legionengine.com
          publish_branch: main
          publish_dir: ./${{ matrix.app }}
          force_orphan: true
          cname: ${{ matrix.app }}.legionengine.com
